# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rakshit Jain
email: rakshit.jain@iitb.ac.in
description: >
  Hi, I am Rakshit, Currently an applied physics graduate student at Cornell.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rj2808.github.io" # the base hostname & protocol for your site
twitter_username: rj28081
github_username: rj2808

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: rj2808
disqus_shortname:
plugins:
  - jekyll-seo-tag

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
